### ISSUE TITLE
Indico importer plugin - missing documentation

### ISSUE THREAD

**Issue by fockeRR** [indico/indico-plugins#17]
Hi,
I need to implement a custom importer, which reads the data from a CSV file and imports them to the indico. After successfully importing the papers, I would like to group them into sessions using Indico. I'm using Indico 1.2. Where I can find a detailed documentation how to start with this stuff?
thanks for your help,
Michał

**Comment by ThiefMaster** [comment]
All plugins in this repository are currently for Indico 1.9.x/2.0 - since 1.9.x are internal releases not recommended for outside users documentation has extremely low priority. But we do intend to have proper documentation for 2.0.

Developing for 1.2 is generally harder (due to a legacy codebase), but maybe [these slides](https://indico.cern.ch/event/235520/session/3/contribution/30/attachments/394630/548854/IndicoWorkshop_PluginDevelopment.pdf) help you (you'll also want to have a look at the existing invenio importer plugin that's part of the indico 1.2 codebase)

**Comment by fockeRR** [comment]
@ThiefMaster thanks for the clarfication.
