### ISSUE TITLE
Bad Request After On payment processing INDICO bug

### ISSUE THREAD

**Issue by tejastank** [indico/indico-plugins#52]
Hello Responsible,

I had build one plugin for payment.

Checkout -> payment -> inidco controller -> success

here via code payment will be deducted, but on page it shows "Bad Request" error message.

I don't even getting any error message on log or not identifying how it comes.

So idoco framework don't tell where exact issue for "Bad Request"

Also strange happen, when I had bad request message on page and in case I refered it works.

But I had to manually fresh every time, which seesm not good solution over indico platform.

Kinldy guide me what steps to carry to resolve it.

**Comment by ThiefMaster** [comment]
`indico.log` should include details on the error (try using a higher log level such as INFO or even DEBUG in `logging.conf` if you don't have details there). Either way, questions about custom code should include the code in question (in this case the code of your RH subclass) and are better asked on IRC (which you already did, so I'm closing this issue here).

**Comment by tejastank** [comment]
@ThiefMaster great thanks, ThiefMaster CSRF_ENABLED = False worked succesful.

BIG THANK YOU.
