### ISSUE TITLE
storage_s3: Password saved in plain text in database

### ISSUE THREAD

**Issue by martinclaus** [indico/indico-plugins#78]
The password that is set in the plugin settings is stored as plain text in the database. This is actually true for any password that is set via a `IndicoPasswordField` in any plugin.

I do not think that this is desirable or am I paranoid?

**Comment by ThiefMaster** [comment]
The plain text password in the S3 plugin is only for an API endpoint that provides a list of buckets (so it can be consumed e.g. by a backup tool).
Could it be hashed? Yes, certainly. But this is more like an API token than a password (and if we had a better API, it **would be one** instead of a plugin setting), so the benefit of being able to see it is actually higher than the minimal security gain of hashing it.

Someone getting access to your database or an admin account could see all the data from all the events - that'd be much more of a problem than someone seeing a list of buckets which are semi-public anyway (since downloading a file stored there will include the bucket name in the URL).

FYI, the credentials used to *access* S3 are stored on disk, and not accessible at all to someone without shell access.

---

And for all the other places where the field is used:

- event access key: A "password" that's meant to be shared with many people. So again, something where it makes sense for the event manager to be able to see it
- vidyo plugin: the password is used to access the vidyo API, so indico needs to have it in plaintext. Sure, could be hidden from admins so they can only change but not see it, but admins should be trusted.
- various CERN plugins: same case like with vidyo
